dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false
services:
  - docker

jobs:
  include:
    - stage: Build
      name: "Build Docker Images"
      install: cd scripts && npm ci && cd ..
      script: node scripts/build
      env:
        # DEPLOY_SETTINGS_JSON='{"CI":[{"type":"docker","options":{"user":"","pass":""}}]}'
        - secure: U/M6GsPQ0/CreRns/ggqFcDcqUBYzfw6OGxtpqcUHJzfm1ynnvOakWPrYi+TQOLX+yAyi43/uMMKQ10cHJpyJZgKqC4mKDQrjRWVIq8t/r/iZ0BkRy/V0Zqp0X1y411wsHMX6n1aNccsxpYJkrjNntoM4kS0KrlPr5BYaxP/pvNaDt1gdNUKP7w2eoLJyA4q8pbU/VCZ6ssKh6EJaGT5WWoIWO17iLTXY8O+7LLXc8iODqXokHf/6A+dbvmKQn4TPs8lLpWAlGD7TzG8OaMZuvk9ROm0VmOys/vKjU43oFHB70NwRT9odanVVJK8s486MOU6V2oR3F9tU8+sRMgWZg1/ELUOyOdj0iPIj7701ibvW8tZWehfezRNdgk9zNf0PyUWpE4ndbyVp2ejKMlKOKlqvlw+KQKich5lvEq70jKIPt4bU5XHc3TpsyxXlrSZ74Fr9m0PAWk2rrcock540FNAwZOu4NfZ+ooSVCSSiJN3Woe8E3si0Hpeshp2s98hOy2FErmxaAXuEmupkKs5Nxqrp93cPUVaWBy1l0eOcpJEWL9/TWnLk5wLFW4jl/GGzDUvn4bAH5LveV33vDQ3yENwFeKb9wEImwqSd+OMZS5B6b3ZGNujlil9on8NrbrDjs9uDX4VK9QY28+i8MP4K2EjGYH7FQAy6mRpywLv6FI=

    - stage: Test
      name: "Unit Tests"
      env:
        - image_tag=peyk/client:unstable-solution
      script: echo ToDo

    - stage: Deploy
      name: "Deploy"
      script: skip
      install:
        - cd scripts && npm ci && cd ..
        - docker pull peyk/client:unstable
      env:
        # DEPLOY_SETTINGS_JSON='{"Production":[
        #   {"type":"docker","options":{"source":"peyk/client:unstable","target":"peyk/client","user":"","pass":""}},
        #   {"type":"heroku","options":{"app":"peyk-client","source":"peyk/client","dyno":"web","user":"","token":""}}
        # ]}'
        - secure: 2thvmIp7p+q46PkZwQq/JimRpD2lbh0PEmjGEDWTDQ+Lx3YgnjWqSJ9x3ukYO09WHOLSiADKhxWTKGsfutqVqrLx87gmkie9hAsXxlYBcOK1xnN/K31gndsF4GelqngzeK31AFBYzX8nTp3KljpXNJcqsNZQyQ7s5BW0WJTXgGaDsHKMYN5wseuwCUn21zwMwkp+qpXJijRnVq4308HVc8z5y3P8VdZYB4g5AWVAQ7kKuTls3kPwFrvj8SokuXR5uL6CjhzEA+CS93SbschnGfdXHJo89Myo8FeekHmZv8tyylBTSaZ+oXC5hpYSf95QMvfkguaI5h4Kl0mHnIEfv6MYQWr3sFJL05A9K5AYKlbejJ6UPtt7sF11OXxNy5Z3QJv57I4+N9AOPmW4mBNyo4spbkZhCcfCqsbv6dX0HOfcfSZl/EGZBDnlqodCU26RlySAHP6ZxIhY77H8AbIr5bca6kQtjj3Erj1I3KDZioZ50Q+9uK0HW3JJ5q7u8iBpO4yeOXG+MlR9/g+dRXSP7OZsiHLO0lKcR8qZU+6sJ1YbKYTceIXovHQp7XRnYFf5TUQFajJftVFuVqv2FkcIOGqt52H/mY/kR+ySN/rZntWMOTSTpySmOagig5iikVjy/LK4ZlCMIa0otv/3zhUsOnCh81yUKxanoQgNXTua5c0=

      deploy:
        - provider: script
          skip_cleanup: true
          script: node scripts/deploy Production
          on:
            branch: master


# Disable "Build pushed pull requests"
